trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
    persistCredentials: true
  - script: |
      git checkout master
      git config --local user.name "Subhashini2610"
      git config --local user.email "subhashini94@gmail.com"
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      mavenAuthenticateFeed: true
      jdkVersionOption: '11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: '--settings $(Agent.TempDirectory)/settings.xml --batch-mode release:prepare -Darguments="-Dmaven.javadoc.skip=true" release:perform'
  - task: Docker@2
    inputs:
      containerRegistry: 'azdev'
      repository: 'azdev'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'