apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdev
  template:
    metadata:
      labels:
        app: azdev
    spec:
      containers:
        - name: azdev
          image: subhashini9426/firstimage
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: cred
---
apiVersion: v1
kind: Service
metadata:
  name: azdev
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: azdev